import tkinter
root = tkinter.Tk()
chatbereich = tkinter.Frame(root)
chatbereich.pack(side=tkinter.TOP, expand = 1, fill = tkinter.BOTH)
scrollbar = tkinter.Scrollbar(chatbereich)
scrollbar.pack(side=tkinter.RIGHT, fill = tkinter.Y)
fenster = tkinter.Text(chatbereich, yscrollcommand=scrollbar.set)
fenster.pack(side=tkinter.LEFT, expand = 1, fill = tkinter.BOTH)
scrollbar.config(command=fenster.yview)
root.mainloop()
